
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/appinfodb?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
# jpa:
#  database: mysql
# show-sql: true
#配置jsp视图页面
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
#mybatis配置mapper映射文件
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.app.entity
  configuration:
    map-underscore-to-camel-case: true
      #  thymeleaf:
      #    encoding: UTF-8
      #   servlet:
      #      content-type: text/html
      #    cache: false
      #    mode: LEGACYHTML5
      #    prefix: classpath:/templates/
      #    suffix: .html
server:
  port: 8088